### ISSUE TITLE
Probably to stupid?

### ISSUE THREAD

**Issue by BenSpex** [insurify/github-asana-action#10]
Hi, 

I get this error 
```
Run insurify/github-asana-action@v2.0.0
  with:
    asana-pat: ***
    task-comment: Github action: 
    trigger-phrase: ASANA TASK:
Error: Cannot read property 'html_url' of undefined
```

My commit details:
Testing Asana GitHub Action
ASANA TASK: https://app.asana.com/0/

and my yml:
```
on: pull_request
  # Trigger the workflow on push or pull request,
  # but only for the main branch
jobs:
  asana:
    runs-on: ubuntu-latest
    steps:
    - name: Add to Asana
      uses: insurify/github-asana-action@v2.0.0
      with:
        # Asana Public Access Token.
        asana-pat: ${{ secrets.ASANA }}
        # Provide text, which will add a comment with the pull request link to the asana task.
        task-comment: '* Pull Request: '
        # Prefix before the task i.e ASANA TASK: https://app.asana.com/1/2/3
        trigger-phrase: "ASANA TASK:"
```

What am I doing wrong?

**Comment by katehedgpeth** [comment]
Hi @BenSpex! In all of our implementations, we specify a `type` under `pull_request`, like this:

```yml
on:
  pull_request:
    types: [opened] # or [closed, edited, etc]
```

Try that and see if it works?
